feat(loss detector): migrate loss-detector to App SDK 3.0.1
intel-retail/rtsf-at-checkout-reference-design pull request #87
Opened 2023-10-13 23:08 UTC by seanohair22

## PR Checklist

- [ ] Added label to the Pull Request for easier discoverability and search
- [x] Commit Message meets guidelines as indicated in the URL https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md
- [x] Every commit is a single defect fix and does not mix feature addition or changes
- [ ] Unit Tests have been added for new changes
- [ ] Updated Documentation as relevant to the changes
- [ ] All commented code has been removed
- [ ] If you've added a dependency, you've ensured license is compatible with repository license and clearly outlined the added dependency.
- [ ] PR change contains code related to security
- [ ] PR introduces changes that breaks compatibility with other modules (If YES, please provide details below)

## What are you changing?

Migrating loss_detector to EdgeX App SDK 3.0.1
## Issue this PR will close

close: #**77**
closes: #77 
## Anything the reviewer should know when reviewing this PR?

## Test Instructions if applicable

- Run `make loss-detector`
- Comment out lines 27 - 82 in `docker-compose.loss-detection.yml`
- Run `make run-base`
- Optional: Run `make run-portainer` to check logs of loss-detector container
- Optional: Run `docker compose -f loss-detection-app/docker-compose.portainer.yml down` to close Portainer

## If the there are associated PRs in other repositories, please link them here (i.e. intel-retail/rtsf-at-checkout-reference-design )

2023-10-16 17:29 UTC, lenny-intel requested changes

2023-10-16 17:29 UTC, lenny-intel commented on rtsf-at-checkout-loss-detector/Dockerfile
> +CMD [ "/loss-detector", "--cp=consul://edgex-core-consul:8500", "--registry", "--configDir=/res"]
`/res` is the default, so remove the redundant flag.

```suggestion
CMD [ "/loss-detector", "--cp=consul://edgex-core-consul:8500", "--registry"]
```

2023-10-16 17:29 UTC, lenny-intel commented on rtsf-at-checkout-loss-detector/res/configuration.yaml
> +  ServerBindAddr: ''
This is the default, so it can be removed
```suggestion

```

2023-10-17 18:37 UTC, lenny-intel approved these changes
LGTM

2023-10-17 22:35 UTC, brian-intel approved these changes

2023-10-18 01:01 UTC, merged