Upgrade event simulator to use edge x3.0 /v3
intel-retail/rtsf-at-checkout-reference-design pull request #89
Opened 2023-10-17 17:16 UTC by jim-wang-yutsung

## PR Checklist

- [x] Added label to the Pull Request for easier discoverability and search
- [x] Commit Message meets guidelines as indicated in the URL https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md
- [x] Every commit is a single defect fix and does not mix feature addition or changes
- [ ] Unit Tests have been added for new changes
- [ ] Updated Documentation as relevant to the changes
- [ ] All commented code has been removed
- [ ] If you've added a dependency, you've ensured license is compatible with repository license and clearly outlined the added dependency.
- [ ] PR change contains code related to security
- [ ] PR introduces changes that breaks compatibility with other modules (If YES, please provide details below)

## What are you changing?

## Issue this PR will close

close: #**76**

## Anything the reviewer should know when reviewing this PR?

## Test Instructions if applicable

## If the there are associated PRs in other repositories, please link them here (i.e. intel-retail/rtsf-at-checkout-reference-design )

2023-10-17 18:37 UTC, lenny-intel approved these changes
LGTM

2023-10-17 22:35 UTC, brian-intel approved these changes

2023-10-17 22:36 UTC, brian-intel requested changes

2023-10-17 22:36 UTC, brian-intel commented on rtsf-at-checkout-event-simulator/main.go
>  	"encoding/json"
Update copyright date

2023-10-17 23:00 UTC, jim-wang-intel commented on rtsf-at-checkout-event-simulator/main.go
>  	"encoding/json"
updated

2023-10-18 00:54 UTC, brian-intel approved these changes

2023-10-19 15:25 UTC, merged